### ISSUE TITLE
Code block rendering issue

### ISSUE THREAD

**Issue by hientranea** [obiscr/ChatGPT#250]
## Descripion 
It seems that there is a bug regarding code block rendering. The code block only renders correctly after I switch between the conversations. I have also tested it with various prompts and the GPT model, but the issue still persists. Therefore, I believe that it originates from the plugin, not the ChatGPT response.

https://github.com/obiscr/ChatGPT/assets/40749524/adca029b-2135-4d81-aa8d-ddec7171e2d0

Tested on:
- RubyMine version 2023.1.3
- Plugin version 3.0.1-231

**Comment by obiscr** [comment]
Currently code blocks are only parsed as codeblock if they return the standard markdown format, similar to this structure
\`\`\`
some code
\`\`\`

However, because of the uncertainty of AI, the returned content sometimes doesn't use the above format, so there are problems.

I tested it on the same day, however the problem could not be reproduced. Could you please tell me if all your code blocks have this problem? 
Also if you can, please send `idea.log` and export the current problematic conversation together to my email: wuzi@obiscr.com

**Comment by obiscr** [comment]
This issue is out of date.
