### ISSUE TITLE
Bug with indent in Intellij Ultimate

### ISSUE THREAD

**Issue by mo2menelzeiny** [obiscr/ChatGPT#258]
There is a bug where the indentation now in intellij does not work properly if the plugin is enabled, I believe it's because of the new shortcuts with for latest feature of code suggestion.

Scenario:
1- Enable the plugin
2- Press tab key in any line of code (python)

Expected:
The tab key should respect the indentation style and in my case output 4 spaces

Actual:
The tab key ignores the indentation styles and outputs tab character regardless

When I disable the plugin or Tab Action in Keybindings everything goes back to normal

**Comment by decorus-kazuma** [comment]
I have the same problem.

**Comment by obiscr** [comment]
Thanks, currently when Tab key is pressed, it will determine the cursor position, if the cursor position is at the end of the line or a new blank line (any position), it will execute the Inline-complete action, otherwise it will execute the default action of Tab key.

As a temporary solution, it is recommended to use the [3.0.1 version](https://plugins.jetbrains.com/plugin/20603-chatgpt--easycode/versions/stable/353123) first. You can download it at [here](https://plugins.jetbrains.com/plugin/download?rel=true&updateId=353123), and manual installation(**Uninstall the 3.0.3 version at first**).

Also, cause I can't reproduce this locally, please record a gif to give me a better understanding of the situation.

**Comment by fortenforge** [comment]
We've received several reports from users using this plugin that the latest update interferes with our own plugin (Codeium) which also provides inline autocompletion. When users hit tab instead of accepting Codeium's suggestion it just inserts 4 sapces.

**Comment by obiscr** [comment]
Hi, @fortenforge 
I'm currently waiting for further user feedback and we'll fix the problem as soon as we find it.

**Comment by mo2menelzeiny** [comment]
> Thanks, currently when Tab key is pressed, it will determine the cursor position, if the cursor position is at the end of the line or a new blank line (any position), it will execute the Inline-complete action, otherwise it will execute the default action of Tab key.
> 
> As a temporary solution, it is recommended to use the [3.0.1 version](https://plugins.jetbrains.com/plugin/20603-chatgpt--easycode/versions/stable/353123) first. You can download it at [here](https://plugins.jetbrains.com/plugin/download?rel=true&updateId=353123), and manual installation(**Uninstall the 3.0.3 version at first**).
> 
> Also, cause I can't reproduce this locally, please record a gif to give me a better understanding of the situation.

Thanks for your reply, I was able to overcome this, by manually disabling the Tab shortcut key for the plugin in the Intellij Keybindings

![image](https://github.com/obiscr/ChatGPT/assets/22756089/e5b923b8-3b18-49b5-89e3-0e2128450cdd)

I'm not sure how to record a gif to be honest, I will try to do that later.

A simple explanation  to the scenario is:

- when the Plugin is active and you click tab to indent a line in your editor what you expect is the line would follow the indent style of your IDE configuration
- The scenario I explained in the issue is I have the indentation style set to 4 spaces, what I would expect is when I hit tab it would produce 4 spaces
- What actually happens when the plugin is enabled is it produces a tab character and ignores the configured indent style in my IDE

**Comment by rocketpunch-dev** [comment]
I had a similar issue in my case. @obiscr 

![bug_chatgpt_plugin](https://github.com/obiscr/ChatGPT/assets/15686574/8e68148d-a8b4-4a8a-b593-76e6c8d5bdf3)

**Comment by obiscr** [comment]
Thanks for the replies guys, cause I was unable to reproduce it locally. So I tried to fix it in version [3.0.4](https://plugins.jetbrains.com/plugin/20603-chatgpt--easycode/versions/stable/366399) and as a worst case scenario, I also added a switch so that if it still doesn't work, the user tries to disable the feature. the new version is currently under review. Please update to 3.0.4 once it's approved to see if the problem is still there.

![image](https://github.com/obiscr/ChatGPT/assets/28687074/46f4af44-08a2-4199-a129-356fe47431e6)

**Comment by obiscr** [comment]
The new version 3.0.4 has been released, please upgrade to 3.0.4. If the problem still exists, please try to disable Inline Auto Complete via this settings:

![](https://user-images.githubusercontent.com/28687074/255196567-46f4af44-08a2-4199-a129-356fe47431e6.png)
